spring:
  datasource:
    url: jdbc:mysql://localhost/spring_quickly?useLegacyDatetimeCode=false&serverTimezone=UTC
    username: dalei
    password: oarnud9I*test
  sql:
    init:
      mode: always
